#!/usr/bin/env python3
"""Generate developer API documentation from Python signatures and release inputs."""
from __future__ import annotations
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/generated/API.md"
PY_FILES = [ROOT / "build/package_firmware.py", *sorted((ROOT / "deploy").glob("*.py"))]

def py_api(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    rows = [f"### `{path.relative_to(ROOT)}`", ""]
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) or node.name.startswith("_"):
            continue
        if isinstance(node, ast.ClassDef):
            rows.append(f"#### class `{node.name}`")
            doc = ast.get_docstring(node)
            if doc: rows.append(doc.splitlines()[0])
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)) and not child.name.startswith("_"):
                    rows.append(f"- `{ast.unparse(child).split(chr(58), 1)[0]}`")
        else:
            rows.append(f"#### function `{ast.unparse(node).split(chr(58), 1)[0]}`")
            doc = ast.get_docstring(node)
            if doc: rows.append(doc.splitlines()[0])
        rows.append("")
    return rows

def json_api(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    text = "\n".join(line for line in text.splitlines() if "//" not in line)
    data = json.loads(text)
    rows = [f"### `{path.relative_to(ROOT)}`", ""]
    if path.name == "version.json":
        rows += ["| Field | Current value |", "|---|---|"]
        for key in ("schema_version", "version", "branch_name", "commit_id", "output_name"):
            if key in data: rows.append(f"| `{key}` | `{data[key]}` |")
    elif "targets" in data:
        rows += ["Target keys: `device`, `os_id`, `os_version`, `architecture`, `config_files`, `system_config`, `extra_debs`, `runs`, `supervisor_modules`.", ""]
        rows.append("Targets: " + ", ".join(sorted(data["targets"])))
        rows.append("")
    return rows

lines = ["# 自动生成接口契约", "", "> Generated by `system_deployment/tools/generate_api_docs.py`; do not edit manually.", "", "## Python API", ""]
for path in PY_FILES:
    lines.extend(py_api(path))
lines += ["## Release configuration API", ""]
for path in sorted((ROOT / "release").glob("*.json")):
    lines.extend(json_api(path))
lines += ["## Command API", "", "```bash", "./system_deployment/build/build_release.sh [--dry-run]", "sudo ./Middleware-2.0.0-1.run -- --pretest", "sudo ./Middleware-2.0.0-1.run -- --robot-type <ROBOT_TYPE>", "```", ""]
OUT.write_text("\n".join(lines), encoding="utf-8")
print(OUT)
