hardware_body:
  dst: /var/opt/hardware_body.yaml
  entries:
    - models: [H1, U1]
      src: H1+U1/hardware_body.yaml
    - models: [I2, I2-S, I2-D, I2-E, I3-S]
      src: I2/hardware_body.yaml
    - models: [WA1, WA1_400L, WA1_400K, U2_WA1, WA1-S, WA1-D, WA1-E, U2-S, U2-D]
      src: WA1+WA1_400K+WA1_400L+U2_WA1/hardware_body.yaml
    - models: [WA2, WA2_L]
      src: WA2+WA2_L/hardware_body.yaml
    - models: [WA2_LS, WA2-S, WA2-P, WA2-D]
      src: WA2_LS/hardware_body.yaml
    - models: [WA2_TY20]
      src: WA2_TY20/hardware_body.yaml
    - models: [ZYD_V1]
      src: ZYD/hardware_body.yaml


hw_meta:
  dst: /var/opt/hw_meta.yaml
  # entries:
  #   - models: [H1, U1, U2_WA1, U2-S]
  #     src: H1+U1+U2_WA1+U2-S/hw_meta.yaml
  #   - models: [I2, I2-S, I2-D, I2-E]
  #     src: I2/hw_meta.yaml
  #   - models: [WA1, WA1_400K, WA1_400L, WA1-S, WA1-D, WA1-E]
  #     src: WA1+WA1_400K+WA1_400L/hw_meta.yaml
  #   - models: [WA2, WA2_L]
  #     src: WA2+WA2_L/hw_meta.yaml
  #   - models: [WA2_LS]
  #     src: WA2_LS/hw_meta.yaml
  #   - models: [WA2_TY20]
  #     src: WA2_TY20/hw_meta.yaml
