import importlib.util
from pathlib import Path
import tempfile
import unittest


SCRIPT = Path(__file__).resolve().parents[1] / "one_stop/tools/orin-humble/detect_livox_model.py"
SPEC = importlib.util.spec_from_file_location("detect_livox_model", SCRIPT)
detector = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(detector)


class LivoxDetectionTest(unittest.TestCase):
    def test_manual_override_is_validated(self):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "navigation.env"
            path.write_text("# export LIDAR_3D_TYPE=MID360\nexport LIDAR_3D_TYPE='mid360s'\n")
            self.assertEqual(detector.manual_model(path), "MID360S")

    def test_generated_result_is_written_as_a_separate_cache(self):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "navigation/lidar.auto.env"
            detector.write_state(path, "MID360")
            self.assertEqual(
                path.read_text(),
                "# Generated by detect_livox_model.py; do not edit this file.\n"
                "# Set LIDAR_3D_TYPE in navigation.env to override automatic detection.\n"
                "export LIDAR_3D_TYPE=MID360\n",
            )

    def test_sdk_config_uses_the_known_lidar_and_host_addresses(self):
        config = detector.sdk_config("MID360S", "192.168.217.100", "192.168.217.17")
        self.assertEqual(config["Mid360s"]["host_net_info"][0]["host_ip"], "192.168.217.100")
        self.assertEqual(config["lidar_configs"][0]["ip"], "192.168.217.17")
